name = "WebCrawler"
uuid = "8a8dfe4f-faff-4b9f-a9a3-5122e01790e4"
authors = ["Yujung Suh <yujsuh75@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
